docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - "Session Config": config.md
    - "Session Container": container.md
    - "Session Manager": manager.md
    - "Session Save Handlers": save-handler.md
    - "Session Storage": storage.md
    - Validators:
        - Introduction: validators/introduction.md
        - "Http User Agent": validators/httpuseragent.md
        - "Remote Address": validators/remoteaddr.md
        - "CSRF Validator": validator/csrf.md
        - "Writing Custom Validators": validators/writing-custom-validators.md
    - "Application Integration":
        - "Usage in a laminas-mvc application": application-integration/usage-in-a-laminas-mvc-application.md
site_name: laminas-session
site_description: 'Object-oriented interface to PHP sessions and storage.'
repo_url: 'https://github.com/laminas/laminas-session'
extra:
    project: Components
    installation:
      config_provider_class: 'Laminas\Session\ConfigProvider'
      module_class: 'Laminas\Session\Module'
plugins:
    - redirects:
          redirect_maps:
              validator.md: validators/introduction.md
